# Generated Master List for Brainrot Spawn Simulator
# Extracted from: https://stealabrainrot.fandom.com/wiki/Category:Brainrots

MASTER_LIST = [
    {"name": "1x1x1x1", "rarity": "Common", "spawn_weight": 40},
    {"name": "67", "rarity": "Common", "spawn_weight": 40},
    {"name": "Admin Lucky Block", "rarity": "Common", "spawn_weight": 40},
    {"name": "Agarrini La Palini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Alessio", "rarity": "Common", "spawn_weight": 40},
    {"name": "Anpali Babel", "rarity": "Common", "spawn_weight": 40},
    {"name": "Antonio", "rarity": "Common", "spawn_weight": 40},
    {"name": "Aquanut", "rarity": "Common", "spawn_weight": 40},
    {"name": "Avocadini Antilopini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Avocadini Guffo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Avocadorilla", "rarity": "Common", "spawn_weight": 40},
    {"name": "Ballerina Cappuccina", "rarity": "Common", "spawn_weight": 40},
    {"name": "Ballerino Lololo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bambini Crostini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bambu Bambu Sahur", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bananita Dolphinita", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bananito Bandito", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bandito Axolito", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bandito Bobritto", "rarity": "Common", "spawn_weight": 40},
    {"name": "Belula Beluga", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bisonte Giuppitere", "rarity": "Common", "spawn_weight": 40},
    {"name": "Blackhole Goat", "rarity": "Common", "spawn_weight": 40},
    {"name": "Blueberrinni Octopusini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bombardini Tortinii", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bombardiro Crocodilo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bombombini Gusini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Boneca Ambalabu", "rarity": "Common", "spawn_weight": 40},
    {"name": "Brainrot God Lucky Block", "rarity": "Common", "spawn_weight": 40},
    {"name": "Brasilini Berimbini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Brr Brr Patapim", "rarity": "Common", "spawn_weight": 40},
    {"name": "Brr es Teh Patipum", "rarity": "Common", "spawn_weight": 40},
    {"name": "Brri Brri Bicus Dicus Bombicus", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bruto Gialutto", "rarity": "Common", "spawn_weight": 40},
    {"name": "Buho De Fuego", "rarity": "Common", "spawn_weight": 40},
    {"name": "Bulbito Bandito Traktorito", "rarity": "Common", "spawn_weight": 40},
    {"name": "Burbaloni Luliloli", "rarity": "Common", "spawn_weight": 40},
    {"name": "Burguro And Fryuro", "rarity": "Common", "spawn_weight": 40},
    {"name": "Burrito Bandito", "rarity": "Common", "spawn_weight": 40},
    {"name": "Cacasito Satalito", "rarity": "Common", "spawn_weight": 40},
    {"name": "Cachorrito Melonito", "rarity": "Common", "spawn_weight": 40},
    {"name": "Cacto Hipopotamo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Capi Taco", "rarity": "Common", "spawn_weight": 40},
    {"name": "Capitano Moby", "rarity": "Common", "spawn_weight": 40},
    {"name": "Cappuccino Assassino", "rarity": "Common", "spawn_weight": 40},
    {"name": "Cappuccino Clownino", "rarity": "Common", "spawn_weight": 40},
    {"name": "Caramello Filtrello", "rarity": "Common", "spawn_weight": 40},
    {"name": "Carloo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Carrotini Brainini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Cavallo Virtuoso", "rarity": "Common", "spawn_weight": 40},
    {"name": "Celularcini Viciosini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chachechi", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chef Crabracadabra", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chicleteira Bicicleteira", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chicleteirina Bicicleteirina", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chihuanini Taconini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chillin Chili", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chimpanzini Bananini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chimpanzini Spiderini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Chipso and Queso", "rarity": "Common", "spawn_weight": 40},
    {"name": "Cocofanto Elefanto", "rarity": "Common", "spawn_weight": 40},
    {"name": "Cocosini Mama", "rarity": "Common", "spawn_weight": 40},
    {"name": "Combinasions", "rarity": "Common", "spawn_weight": 40},
    {"name": "Corn Corn Corn Sahur", "rarity": "Common", "spawn_weight": 40},
    {"name": "Crabbo Limonetta", "rarity": "Common", "spawn_weight": 40},
    {"name": "Developini Braziliaspidini", "rarity": "Common", "spawn_weight": 40},
    {"name": "Dragon Cannelloni", "rarity": "Common", "spawn_weight": 40},
    {"name": "Dug dug dug", "rarity": "Common", "spawn_weight": 40},
    {"name": "Dul Dul Dul", "rarity": "Common", "spawn_weight": 40},
    {"name": "Elefanto Frigo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Esok Sekolah", "rarity": "Common", "spawn_weight": 40},
    {"name": "Espresso Signora", "rarity": "Common", "spawn_weight": 40},
    {"name": "Eviledon", "rarity": "Common", "spawn_weight": 40},
    {"name": "Extinct Ballerina", "rarity": "Common", "spawn_weight": 40},
    {"name": "Extinct Matteo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Extinct Tralalero", "rarity": "Common", "spawn_weight": 40},
    {"name": "Fluriflura", "rarity": "Common", "spawn_weight": 40},
    {"name": "Fragola La La La", "rarity": "Common", "spawn_weight": 40},
    {"name": "Frankentteo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Frigo Camelo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Frio Ninja", "rarity": "Common", "spawn_weight": 40},
    {"name": "Frogato Pirato", "rarity": "Common", "spawn_weight": 40},
    {"name": "Ganganzelli Trulala", "rarity": "Common", "spawn_weight": 40},
    {"name": "Gangster Footera", "rarity": "Common", "spawn_weight": 40},
    {"name": "Garama and Madundung", "rarity": "Common", "spawn_weight": 40},
    {"name": "Gattatino Neonino", "rarity": "Common", "spawn_weight": 40},
    {"name": "Gattatino Nyanino", "rarity": "Common", "spawn_weight": 40},
    {"name": "Gattito Tacoto", "rarity": "Common", "spawn_weight": 40},
    {"name": "Girafa Celestre", "rarity": "Common", "spawn_weight": 40},
    {"name": "Glorbo Fruttodrillo", "rarity": "Common", "spawn_weight": 40},
    {"name": "Gorillo Subwoofero", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Gorillo Watermelondrillo", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Graipuss Medussi", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Guerriro Digitale", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Headless Horseman", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Jacko Jack Jack", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Job Job Job Sahur", "rarity": "Rare", "spawn_weight": 25},
    {"name": "John Pork", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Karker Sahur", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Karkerkar Kurkur", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Ketchuru and Musturu", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Ketupat Kepat", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Krupuk Pagi Pagi", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Cucaracha", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Extinct Grande", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Grande Combinasion", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Karkerkar Combinasion", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Sahur Combinasion", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Secret Combinasion", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Spooky Grande", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Supreme Combinasion", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Taco Combinasion", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Vacca Jacko Linterino", "rarity": "Rare", "spawn_weight": 25},
    {"name": "La Vacca Saturno Saturnita", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Las Cappuchinas", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Las Sis", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Las Tralaleritas", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Las Vaquitas Saturnitas", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Lerulerulerule", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Limited Stock Brainrots", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Lionel Cactuseli", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Lirilì Larilà", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los 67", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Bombinitos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Bros", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Chicleteiras", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Combinasionas", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Crocodillitos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Hotspotsitos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Jobcitos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Karkeritos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Matteos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Mobilis", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Noobinis", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Nooo My Hotspotsitos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Orcalitos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Primos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Spyderinis", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Tacoritas", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Tipi Tacos", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Tortus", "rarity": "Rare", "spawn_weight": 25},
    {"name": "Los Tralaleritos", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Los Tungtungtungcitos", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Magi Ribbitini", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Malame Amarele", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Mangolini Parrocini", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Mariachi Corazoni", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Mastodontico Telepiedone", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Matteo", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Meowl", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Mieteteira Bicicleteira", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Money Money Puggy", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Mummio Rappitto", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Mythic Lucky Block", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Noo my Candy", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Noo my examine", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Noobini Pizzanini", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Nooo My Hotspot", "rarity": "Epic", "spawn_weight": 15},
    {"name": "NotYuiopeem/Burbaloni rebalance", "rarity": "Epic", "spawn_weight": 15},
    {"name": "NotYuiopeem/Noobini Rebalance", "rarity": "Epic", "spawn_weight": 15},
    {"name": "NotYuiopeem/Pipi corni rebalance", "rarity": "Epic", "spawn_weight": 15},
    {"name": "NotYuiopeem/Pipi rebalance", "rarity": "Epic", "spawn_weight": 15},
    {"name": "NotYuiopeem/Talpa di feró rebalance", "rarity": "Epic", "spawn_weight": 15},
    {"name": "NotYuiopeem/Tim cheese rebalance", "rarity": "Epic", "spawn_weight": 15},
    {"name": "NotYuiopeem/bomb pig rebalance", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Nuclearo Dinossauro", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Odin Din Din Dun", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Orangutini Ananassini", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Orcalero Orcala", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Orcalita Orcala", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pakrahmatmamat", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pakrahmatmatina", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pandaccini Bananini", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Penguino Cocosino", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Perochello Lemonchello", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Perrito Burrito", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pi Pi Watermelon", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Piccione Macchina", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Piccionetta Machina", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pinealotto Fruttarino", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pipi Avocado", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pipi Corni", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pipi Kiwi", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pipi Potato", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pop Pop Pop Pop Sahur", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pot Hotspot", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Pot Pumpkin", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Quackula", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Quesadilla Crocodila", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Quesadillo Vampiro", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Quivioli Ameleonni", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Raccooni Jandelini", "rarity": "Epic", "spawn_weight": 15},
    {"name": "Rhino Helicopterino", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Rhino Toasterino", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "SOMEONEWHODOESNOTCARE", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "SWAQ38/Sandbox", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Salad fish master", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Salamino Penguino", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Sammyni Spyderini", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Secret Lucky Block", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Sigma Boy", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Sigma Girl", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Signore Carapace", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Sin mei chan/Page Archive", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Skibidi Toilet", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Skull Skull Skull", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Smurf Cat", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Snailenzo", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Spaghetti Tualetti", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Spioniro Golubiro", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Spooky and Pumpky", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Squalanana", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Statutino Libertino", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Strawberrelli Flamingelli", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Strawberry Elephant", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Svinina Bombardino", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Ta Ta Ta Ta Sahur", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tacorita Bicicleta", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Talpa Di Fero", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tang Tang Keletang", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tartaragno", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tartaruga Cisterna", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Te Te Te Sahur", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tentacolo Tecnico", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Ti Ti Ti Sahur", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tictac Sahur", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tigrilini Watermelini", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tigroligre Frutonni", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tim Cheese", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tipi Topi Taco", "rarity": "Legendary", "spawn_weight": 10},
    {"name": "Tirilikalika Tirilikalako", "rarity": "God", "spawn_weight": 5},
    {"name": "To to to Sahur", "rarity": "God", "spawn_weight": 5},
    {"name": "Tob Tobi Tobi", "rarity": "God", "spawn_weight": 5},
    {"name": "Toiletto Focaccino", "rarity": "God", "spawn_weight": 5},
    {"name": "Torrtuginni Dragonfrutini", "rarity": "God", "spawn_weight": 5},
    {"name": "Tracoducotulu Delapeladustuz", "rarity": "God", "spawn_weight": 5},
    {"name": "Tractoro Dinosauro", "rarity": "God", "spawn_weight": 5},
    {"name": "Tralaledon", "rarity": "God", "spawn_weight": 5},
    {"name": "Tralalero Tralala", "rarity": "God", "spawn_weight": 5},
    {"name": "Tralalita Tralala", "rarity": "God", "spawn_weight": 5},
    {"name": "Trenostruzzo Turbo 3000", "rarity": "God", "spawn_weight": 5},
    {"name": "Trenostruzzo Turbo 4000", "rarity": "God", "spawn_weight": 5},
    {"name": "Tric Trac Baraboom", "rarity": "God", "spawn_weight": 5},
    {"name": "Trippi Troppi", "rarity": "God", "spawn_weight": 5},
    {"name": "Trippi Troppi Troppa Trippa", "rarity": "God", "spawn_weight": 5},
    {"name": "Trulimero Trulicina", "rarity": "God", "spawn_weight": 5},
    {"name": "Tukanno Bananno", "rarity": "God", "spawn_weight": 5},
    {"name": "Unclito Samito", "rarity": "God", "spawn_weight": 5},
    {"name": "Urubini Flamenguini", "rarity": "God", "spawn_weight": 5},
    {"name": "Vampira Cappuccina", "rarity": "God", "spawn_weight": 5},
    {"name": "Vulturino Skeletono", "rarity": "God", "spawn_weight": 5},
    {"name": "Wombo Rollo", "rarity": "God", "spawn_weight": 5},
    {"name": "Yess my examine", "rarity": "God", "spawn_weight": 5},
    {"name": "Zibra Zubra Zibralini", "rarity": "God", "spawn_weight": 5},
    {"name": "Zombie Tralala", "rarity": "God", "spawn_weight": 5},
]
