# Generated Master List for Brainrot Spawn Simulator
# Extracted from: https://stealabrainrot.fandom.com/wiki/Category:Brainrots

MASTER_LIST = [
    {"name": "1x1x1x1", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/39/1x1x1x1t.png"},
    {"name": "67", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/83/BOIIIIIII_SIX_SEVEN_%F0%9F%98%82%F0%9F%98%82%F0%9F%98%82%F0%9F%98%82%F0%9F%98%82%F0%9F%98%82%F0%9F%98%82%F0%9F%98%82%F0%9F%98%82%F0%9F%98%82.png"},
    {"name": "Admin Lucky Block", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/7c/AdminLuckyBlock.png"},
    {"name": "Agarrini La Palini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/de/Agarrini_la_Palini.png"},
    {"name": "Alessio", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/71/Testicular_torsion.png"},
    {"name": "Anpali Babel", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/fa/THE_ROCK.png"},
    {"name": "Antonio", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f0/Antonio.png"},
    {"name": "Aquanut", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/86/Astronaut.png"},
    {"name": "Avocadini Antilopini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/1a/Avocadini_Antilopini.png"},
    {"name": "Avocadini Guffo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f5/Avocadini-Guffo.png"},
    {"name": "Avocadorilla", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/85/Avocadorilla.png"},
    {"name": "Ballerina Cappuccina", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/c1/BallerinaRender.png"},
    {"name": "Ballerino Lololo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/c9/Ballerinolololo.png"},
    {"name": "Bambini Crostini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/0a/Untitled208_20250808152208.png"},
    {"name": "Bambu Bambu Sahur", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/da/Bambu_sahur_full_rost.png"},
    {"name": "Bananita Dolphinita", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b1/Dolphin_But_Banana.png"},
    {"name": "Bananito Bandito", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/2a/Screenshot_2025-10-04_132952.png"},
    {"name": "Bandito Axolito", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b1/Bandito_Axolito1.png"},
    {"name": "Bandito Bobritto", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/57/Messi.png"},
    {"name": "Belula Beluga", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/5b/Beluga.png"},
    {"name": "Bisonte Giuppitere", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/1d/Bisonte_Giuppitere_normal.png"},
    {"name": "Blackhole Goat", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/77/Blackhole_goat.png"},
    {"name": "Blueberrinni Octopusini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/d0/NewBlueberrinni.png"},
    {"name": "Bombardini Tortinii", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/af/Bombardini_tortilii.png"},
    {"name": "Bombardiro Crocodilo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/55/A_flying_alligator.png"},
    {"name": "Bombombini Gusini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/ac/Cant_come_up_with_a_funny_joke_for_this_one.png"},
    {"name": "Boneca Ambalabu", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/9c/Boneca_Ambalabu.png"},
    {"name": "Brainrot God Lucky Block", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/4a/Brainrot_God_Gambling_Block.png"},
    {"name": "Brasilini Berimbini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b6/BRABRABRAZILZILZILZIL.png"},
    {"name": "Brr Brr Patapim", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/6d/Lil_wayne.png"},
    {"name": "Brr es Teh Patipum", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/85/Am_i_right_lads_or_am_i_right_lads.png"},
    {"name": "Brri Brri Bicus Dicus Bombicus", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/4e/Berry_berry_bicus_dickus.png"},
    {"name": "Bruto Gialutto", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/cc/Bruto_gialutto.png"},
    {"name": "Buho De Fuego", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/64/Buhodefuego.png"},
    {"name": "Bulbito Bandito Traktorito", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/eb/Five_hotdogs_for_dinner_tonight.png"},
    {"name": "Burbaloni Luliloli", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/31/Burbaloni-Loliloli.png"},
    {"name": "Burguro And Fryuro", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/65/Burguro-And-Fryuro.png"},
    {"name": "Burrito Bandito", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/e6/PoTaTo.png"},
    {"name": "Cacasito Satalito", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/1e/Lebron_james.png"},
    {"name": "Cachorrito Melonito", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/19/Melon.png"},
    {"name": "Cacto Hipopotamo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/af/Cacto_Hipopotamo1.png"},
    {"name": "Capi Taco", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/ac/Capi_Taco.png"},
    {"name": "Capitano Moby", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/ef/Moby.png"},
    {"name": "Cappuccino Assassino", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/4e/Cappuccino_Assassino.png"},
    {"name": "Cappuccino Clownino", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/73/Cappuccinoclown.png"},
    {"name": "Caramello Filtrello", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/bd/Caramello_Filtrello2.png"},
    {"name": "Carloo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/ad/Mateo_fish.png"},
    {"name": "Carrotini Brainini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/ef/Famine.png"},
    {"name": "Cavallo Virtuoso", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/ca/Cavallo_Virtuoso.png"},
    {"name": "Celularcini Viciosini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/38/DO_NOT_GRAB_MY_PHONE%21%21%21.png"},
    {"name": "Chachechi", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/81/ChachechiNew.png"},
    {"name": "Chef Crabracadabra", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/9d/Travis_scott.png"},
    {"name": "Chicleteira Bicicleteira", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/5a/Chicleteira.png"},
    {"name": "Chicleteirina Bicicleteirina", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/83/Chicleteirina_Bicicleteirina.png"},
    {"name": "Chihuanini Taconini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/07/Yo_quiero_taco_bell.png"},
    {"name": "Chillin Chili", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/e0/Chilin.png"},
    {"name": "Chimpanzini Bananini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/47/ChimpanziniBananini.png"},
    {"name": "Chimpanzini Spiderini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/49/Chimpanzini_Spiderini_Secret.webp"},
    {"name": "Chipso and Queso", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f8/Chipsoqueso.png"},
    {"name": "Cocofanto Elefanto", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/d9/Cocofanto.png"},
    {"name": "Cocosini Mama", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/ca/Cocosini_Mama.png"},
    {"name": "Combinasions", "rarity": "Common", "spawn_weight": 40, "image_url": None},
    {"name": "Corn Corn Corn Sahur", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/06/CornSahur.png"},
    {"name": "Crabbo Limonetta", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f9/Mr_krabs.png"},
    {"name": "Developini Braziliaspidini", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/24/Developini_but_Cropped.png"},
    {"name": "Dragon Cannelloni", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/02/Dragoncanneloni.png"},
    {"name": "Dug dug dug", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/66/DUG_DUG_DUG_BRAINROT.png"},
    {"name": "Dul Dul Dul", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/82/Dul_Dul_Dul.png"},
    {"name": "Elefanto Frigo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/ff/Elefanto_Frigo_Transparent.png"},
    {"name": "Esok Sekolah", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/2a/EsokSekolah2.png"},
    {"name": "Espresso Signora", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/48/Espresso_Signora.png"},
    {"name": "Eviledon", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/78/Eviledonn.png"},
    {"name": "Extinct Ballerina", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/74/Dead_art_form.png"},
    {"name": "Extinct Matteo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/0a/Man_im_dead.png"},
    {"name": "Extinct Tralalero", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/cd/Jaws.png"},
    {"name": "Fluriflura", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/77/Fluriflura.png"},
    {"name": "Fragola La La La", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/af/Sammy_the_strawberry.png"},
    {"name": "Frankentteo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/6a/Frankenmtteo.png"},
    {"name": "Frigo Camelo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/a7/Lol_Fridge.png"},
    {"name": "Frio Ninja", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/a3/FrioNinja.png"},
    {"name": "Frogato Pirato", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/cc/Bigfrog.png"},
    {"name": "Ganganzelli Trulala", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b4/Ganganzelli_Trulala.png"},
    {"name": "Gangster Footera", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/7f/King_von.png"},
    {"name": "Garama and Madundung", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/ee/Garamadundung.png"},
    {"name": "Gattatino Neonino", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/40/Gattatinoneonino.png"},
    {"name": "Gattatino Nyanino", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/e4/Gattatin.png"},
    {"name": "Gattito Tacoto", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/67/Gattatino_Nyaninno.png"},
    {"name": "Girafa Celestre", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/70/...---....png"},
    {"name": "Glorbo Fruttodrillo", "rarity": "Common", "spawn_weight": 40, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/da/GlorboFruttodrillo.png"},
    {"name": "Gorillo Subwoofero", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/08/Dubstep_boy.png"},
    {"name": "Gorillo Watermelondrillo", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/ea/Gorillo-Watermelondrillo.png"},
    {"name": "Graipuss Medussi", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b8/Graipuss.png"},
    {"name": "Guerriro Digitale", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/98/Guerrirodigitale.png"},
    {"name": "Headless Horseman", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/ff/Headlesshorseman.png"},
    {"name": "Jacko Jack Jack", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/1c/Jacko_Jack_Jack.png"},
    {"name": "Job Job Job Sahur", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/03/Job.webp"},
    {"name": "John Pork", "rarity": "Rare", "spawn_weight": 25, "image_url": None},
    {"name": "Karker Sahur", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/14/Karker_Sahur.png"},
    {"name": "Karkerkar Kurkur", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/d9/Karkerkar_kurkur.png"},
    {"name": "Ketchuru and Musturu", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/14/Ketchuru.png"},
    {"name": "Ketupat Kepat", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/ac/KetupatKepat.png"},
    {"name": "Krupuk Pagi Pagi", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/54/Cookie_no_bg.png"},
    {"name": "La Cucaracha", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/46/La_Cucaracha.png"},
    {"name": "La Extinct Grande", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/cd/La_Extinct_Grande.png"},
    {"name": "La Grande Combinasion", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/d8/Carti.png"},
    {"name": "La Karkerkar Combinasion", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/2d/Holy_falloff.png"},
    {"name": "La Sahur Combinasion", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/eb/Sahuria.png"},
    {"name": "La Secret Combinasion", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f2/Lasecretcombinasion.png"},
    {"name": "La Spooky Grande", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/51/Spooky_Grande.png"},
    {"name": "La Supreme Combinasion", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/52/SupremeCombinasion.png"},
    {"name": "La Taco Combinasion", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/84/Latacocombi.png"},
    {"name": "La Vacca Jacko Linterino", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/c6/JackoVacca.png"},
    {"name": "La Vacca Saturno Saturnita", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/d6/La_Vaccca_Saturno_Saturnita.png"},
    {"name": "Las Cappuchinas", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/39/Las_Cappuchinas.png"},
    {"name": "Las Sis", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/e8/Las_Sis.png"},
    {"name": "Las Tralaleritas", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f4/LasTralaleritas.png"},
    {"name": "Las Vaquitas Saturnitas", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/e9/Chick_fil_a.png"},
    {"name": "Lerulerulerule", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/55/Image-removebg-preview_%287%29.png"},
    {"name": "Limited Stock Brainrots", "rarity": "Rare", "spawn_weight": 25, "image_url": None},
    {"name": "Lionel Cactuseli", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/7d/Lionel-Cactuseli.png"},
    {"name": "Lirilì Larilà", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/c8/Liliri_Lalira.png"},
    {"name": "Los 67", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/db/Los-67.png"},
    {"name": "Los Bombinitos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/16/Alvin_and_the_chipmunks.png"},
    {"name": "Los Bros", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/53/BROOOOOOOO.png"},
    {"name": "Los Chicleteiras", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/4d/Los_ditos.png"},
    {"name": "Los Combinasionas", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/36/Stop_taking_my_chips_im_just_a_baybeh.png"},
    {"name": "Los Crocodillitos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/95/LosCrocodillitos.png"},
    {"name": "Los Hotspotsitos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/69/Loshotspotsitos.png"},
    {"name": "Los Jobcitos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/af/LosJobcitos.png"},
    {"name": "Los Karkeritos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/a8/Loskarkeritos.png"},
    {"name": "Los Matteos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/8a/LosMatteos.png"},
    {"name": "Los Mobilis", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/27/Losmobil.png"},
    {"name": "Los Noobinis", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/db/Noobinis.png"},
    {"name": "Los Nooo My Hotspotsitos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/cb/LosNooMyHotspotsitos.png"},
    {"name": "Los Orcalitos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/27/Los_orcalitos.png"},
    {"name": "Los Primos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/96/LosPrimos.png"},
    {"name": "Los Spyderinis", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/ff/Los_Spyderinis.png"},
    {"name": "Los Tacoritas", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/40/My_kids_will_also_rob_you.png"},
    {"name": "Los Tipi Tacos", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f2/Los_tipi_tacos.png"},
    {"name": "Los Tortus", "rarity": "Rare", "spawn_weight": 25, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/cb/LosTortuss.png"},
    {"name": "Los Tralaleritos", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/0f/Los_Tralaleritos.png"},
    {"name": "Los Tungtungtungcitos", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/de/The_middle_one_clawed_out_my_eyes.png"},
    {"name": "Magi Ribbitini", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/60/MagiRibbit.png"},
    {"name": "Malame Amarele", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/28/MalameAmarele.png"},
    {"name": "Mangolini Parrocini", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/1c/MANGOES_MANGOES_MANGOES_MANGOES_MANGHOES_MANGOES_MANGOES_MANGOES_MANGOES_MANGOES_BOIIIIII_SIX_SEVEEEEEEEEN.png"},
    {"name": "Mariachi Corazoni", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/5a/MariachiCora.png"},
    {"name": "Mastodontico Telepiedone", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/a5/Clanker.png"},
    {"name": "Matteo", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/7d/Matteofr.png"},
    {"name": "Meowl", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b8/Clear_background_clear_meowl_image.png"},
    {"name": "Mieteteira Bicicleteira", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/6d/24_sin_t%C3%ADtulo_20251023155436.png"},
    {"name": "Money Money Puggy", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/09/Money_money_puggy.png"},
    {"name": "Mummio Rappitto", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b2/Mummio_Rappitto.png"},
    {"name": "Mythic Lucky Block", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f5/THE_FOG_IS_COMING.png"},
    {"name": "Noo my Candy", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/12/Noo_my_candy_transparent.png"},
    {"name": "Noo my examine", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b9/Noo_My_Examen.png"},
    {"name": "Noobini Pizzanini", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/a2/NOOB%21%21%21.png"},
    {"name": "Nooo My Hotspot", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/97/NoMyHotspot.png"},
    {"name": "NotYuiopeem/bomb pig rebalance", "rarity": "Epic", "spawn_weight": 15, "image_url": None},
    {"name": "NotYuiopeem/Burbaloni rebalance", "rarity": "Epic", "spawn_weight": 15, "image_url": None},
    {"name": "NotYuiopeem/Noobini Rebalance", "rarity": "Epic", "spawn_weight": 15, "image_url": None},
    {"name": "NotYuiopeem/Pipi corni rebalance", "rarity": "Epic", "spawn_weight": 15, "image_url": None},
    {"name": "NotYuiopeem/Pipi rebalance", "rarity": "Epic", "spawn_weight": 15, "image_url": None},
    {"name": "NotYuiopeem/Talpa di feró rebalance", "rarity": "Epic", "spawn_weight": 15, "image_url": None},
    {"name": "NotYuiopeem/Tim cheese rebalance", "rarity": "Epic", "spawn_weight": 15, "image_url": None},
    {"name": "Nuclearo Dinossauro", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/99/THERE_ARE_BUGS_UNDER_YOUR_SKIN.png"},
    {"name": "Odin Din Din Dun", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/96/Me_irl.png"},
    {"name": "Orangutini Ananassini", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/69/Banana.png"},
    {"name": "Orcalero Orcala", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/d4/Orcalero_Orcala.png"},
    {"name": "Orcalita Orcala", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/51/IMG_2496.png"},
    {"name": "Pakrahmatmamat", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/e7/Pakrah.png"},
    {"name": "Pakrahmatmatina", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/fa/Pakrematina.png"},
    {"name": "Pandaccini Bananini", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/03/Pandaccini_Bananini.png"},
    {"name": "Penguino Cocosino", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/71/Penguino_Cocosino%28v2%29.png"},
    {"name": "Perochello Lemonchello", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/a2/PeroLemonfulldetial.png"},
    {"name": "Perrito Burrito", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/6d/Yummytacodog.png"},
    {"name": "Pi Pi Watermelon", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/84/Pi_Pi_Watermelon.png"},
    {"name": "Piccione Macchina", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/e2/PIGEONS_ARE_SPIES_MADE_BY_THE_GOVERNMENT.png"},
    {"name": "Piccionetta Machina", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/79/That_one_pink_bird_from_angry_birds.png"},
    {"name": "Pinealotto Fruttarino", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/ba/Pintealotto.png"},
    {"name": "Pipi Avocado", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/91/Pipi_Avocado.png"},
    {"name": "Pipi Corni", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/5e/Pipi_corni.png"},
    {"name": "Pipi Kiwi", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/92/Pipi_Kiwi.png"},
    {"name": "Pipi Potato", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/cc/POTATO.png"},
    {"name": "Pop Pop Pop Pop Sahur", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/39/PopPopSahur.png"},
    {"name": "Pot Hotspot", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/4b/Pot_Hotspot.png"},
    {"name": "Pot Pumpkin", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/5e/PotPumpkin.png.png"},
    {"name": "Quackula", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/23/Quackula.png"},
    {"name": "Quesadilla Crocodila", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/3f/QuesadillaCrocodilla.png"},
    {"name": "Quesadillo Vampiro", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/6b/Quesa_vampiro.png"},
    {"name": "Quivioli Ameleonni", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/c/cd/Quivioli_Ameleonni.png"},
    {"name": "Raccooni Jandelini", "rarity": "Epic", "spawn_weight": 15, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/2d/Raccooni.png"},
    {"name": "Rhino Helicopterino", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/61/UPokf8FmxyJj4JnktOIdNuJvgtV0vcQRYJLslXal.png"},
    {"name": "Rhino Toasterino", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/1a/Untitled210_20250808180116.png"},
    {"name": "Salad fish master", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/71/KingsColeslaw65.png"},
    {"name": "Salamino Penguino", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/59/Salamino-Penguino.png"},
    {"name": "Sammyni Spyderini", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/9/98/Sammy_blud.png"},
    {"name": "Secret Lucky Block", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/3a/SecretLuckyBlock.png"},
    {"name": "Sigma Boy", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/24/Sig_ma_Boy.png"},
    {"name": "Sigma Girl", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/af/SigmaGirl.png"},
    {"name": "Signore Carapace", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/43/Teenage_turtle.png"},
    {"name": "Sin mei chan/Page Archive", "rarity": "Legendary", "spawn_weight": 10, "image_url": None},
    {"name": "Skibidi Toilet", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/47/Placeholder.png"},
    {"name": "Skull Skull Skull", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/5a/Skull_Skull_Skull.png"},
    {"name": "Smurf Cat", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/bb/Smurf_cat.svg"},
    {"name": "Snailenzo", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/40/Snailenzo.png"},
    {"name": "SOMEONEWHODOESNOTCARE", "rarity": "Legendary", "spawn_weight": 10, "image_url": None},
    {"name": "Spaghetti Tualetti", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b8/Spaghettitualetti.png"},
    {"name": "Spioniro Golubiro", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/40/Weed.png"},
    {"name": "Spooky and Pumpky", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/d6/Spookypumpky.png"},
    {"name": "Squalanana", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/05/Squalanana.png"},
    {"name": "Statutino Libertino", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/4d/StatutinoLibertino.png"},
    {"name": "Strawberrelli Flamingelli", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/21/Strawberrelli_Flamingelli.png"},
    {"name": "Strawberry Elephant", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/58/Strawberryelephant.png"},
    {"name": "Svinina Bombardino", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/26/Homicidio_doloso.png"},
    {"name": "SWAQ38/Sandbox", "rarity": "Legendary", "spawn_weight": 10, "image_url": None},
    {"name": "Ta Ta Ta Ta Sahur", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b2/TaTas.png"},
    {"name": "Tacorita Bicicleta", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/0f/Gonna_rob_you_twin.png"},
    {"name": "Talpa Di Fero", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b1/Talpa_Di_Fero.png"},
    {"name": "Tang Tang Keletang", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/8f/TangTang.png"},
    {"name": "Tartaragno", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/d/de/Tartaragnoo.png"},
    {"name": "Tartaruga Cisterna", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/8d/Tartaruga_Cisternaaaa.png"},
    {"name": "Te Te Te Sahur", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/37/Te_Te_Te_Sahur.png"},
    {"name": "Tentacolo Tecnico", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/ac/SQUID_GAME.png"},
    {"name": "Ti Ti Ti Sahur", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/ad/Titititiit.png"},
    {"name": "Tictac Sahur", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/6f/Time_moving_slow.png"},
    {"name": "Tigrilini Watermelini", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/59/Tigrilini_Watermelini1.png"},
    {"name": "Tigroligre Frutonni", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/71/Tigroligre.png"},
    {"name": "Tim Cheese", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/11/Tim_Cheese.png"},
    {"name": "Tipi Topi Taco", "rarity": "Legendary", "spawn_weight": 10, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/72/Tipi_Topi_Taco.png"},
    {"name": "Tirilikalika Tirilikalako", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/2/2f/TirilikalikaTirilikalakoTransparent.png"},
    {"name": "To to to Sahur", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/58/Africa_by_toto_%28to_sahur%29.png"},
    {"name": "Tob Tobi Tobi", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b0/Tob_Tobi_Tobi.png"},
    {"name": "Toiletto Focaccino", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/59/ToilettoFocaccino.png"},
    {"name": "Torrtuginni Dragonfrutini", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/8c/Crack.png"},
    {"name": "Tracoducotulu Delapeladustuz", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/80/Tracoducotulu.png"},
    {"name": "Tractoro Dinosauro", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/43/TractoroDino.png"},
    {"name": "Tralaledon", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/7/79/Brr_Brr_Patapem.png"},
    {"name": "Tralalero Tralala", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/16/TralaleroTralala.png"},
    {"name": "Tralalita Tralala", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/1/15/Tralalita.png"},
    {"name": "Trenostruzzo Turbo 3000", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/30/Trenostruzzo_Turbo_3000.png"},
    {"name": "Trenostruzzo Turbo 4000", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/b/b0/Trenostruzzo4000.png"},
    {"name": "Tric Trac Baraboom", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/5/5a/Tric-Trac-Baraboom-5.png"},
    {"name": "Trippi Troppi", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/f0/Trippi_Troppi.png"},
    {"name": "Trippi Troppi Troppa Trippa", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/a/a4/Trippi_Troppi_Trooppi_TrooaaapppaaHELP_IM_ABOUT_TO_GET_INTO_A_CAR_CRASH.png"},
    {"name": "Trulimero Trulicina", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/fa/Untitled211_20250809125319.png"},
    {"name": "Tukanno Bananno", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/87/Tukanno_Bananno.png"},
    {"name": "Unclito Samito", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/4/4c/Elon_musk.png"},
    {"name": "Urubini Flamenguini", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/3/36/Currently_on_fire.png"},
    {"name": "Vampira Cappuccina", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/60/VampiraCappuccina.png"},
    {"name": "Vulturino Skeletono", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/e/e0/Vulturino.png"},
    {"name": "Wombo Rollo", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/0/0c/Wombo.png"},
    {"name": "Yess my examine", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/8/8f/Yessmyexamine.png"},
    {"name": "Zibra Zubra Zibralini", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/f/fc/Zibra_Zubra_Zibralini.png"},
    {"name": "Zombie Tralala", "rarity": "God", "spawn_weight": 5, "image_url": "https://static.wikia.nocookie.net/stealabr/images/6/62/ZombieTralala.png"},
]
